### ISSUE TITLE
개인통관부호 입력 UI 변경

### ISSUE THREAD

**Issue by devyih** [arckjh/mdoc#67]
# 요청
- 서비스기획 산출물 : https://drive.google.com/drive/folders/14FzY-qMkkjMxkayl-pDr45Ljb-9nt2tX
- Taskworld : https://asia-enterprise.taskworld.com/5b0df518a3b486513ef4f739/#/project/337/task/8631
- Slack : https://mustit.slack.com/archives/CDV64HN8H/p1544434643009700

# 업무
- 개발 (윤이현 / 12. 11)
- 기능 복원 (윤이현 / 12. 13)
- 기획 변경에 따른 수정 처리 (윤이현 / 12. 17)
- 기능 복원 (윤이현 / 12. 19)
- 퍼블리싱 (유지호  / 19.01.15 ~ 16)
- 개발 (오종윤 / 19.01.16 ~ 18)
- 결함 및 수정 처리 (오종윤 / 19.01.21)

# 이슈
- 기획 방향성 변경으로 인해 차후 디자인 및 개발 업무 일정 수립 후 재 진행하기로 협의됨 (12. 19)

# 테스트
- 해외 상품 구매시 구매자에게 직접 배송되는 경우 개인통관고유 부호/주민등록번호/여권번호/입력안함 값이 DB에 입력되는지 확인한다.(PC,Mobile)
- 해외 상품 구매시 구매자에게 직접 배송되는 경우 통관정보 수집,제공에 동의에 미체크시 경고 팝업창이 발생한다.(PC,Mobile)
- 해외 상품 구매시 구매자에게 직접 배송되는 경우를 제외한 나머지 경우 개인통관고유 부호/주민등록번호/여권번호/입력안함 값이 안나오는지 확인한다.(PC,Mobile)
- 해외 상품 구매시 구매자에게 직접 배송되는 경우를 제외한 나머지 경우 통관정보 수집,제공에 동의란이 보이지 않는지 확인한다.(PC,Mobile)
- 주문이 완료되야 한다(PC,Mobile)

# QA간 추가 요청 사항

- 개인 통관부호/주민등록번호/여권번호 미입력하고 필수체크 선택할시에 바로 alert로 안내 문구 제공. "개인통관고유부호를 입력해주세요"
- 통관 고유번호가 13자리 초과 또는 작을 경우 바로 alert로 안내 문구 제공. "개인고관고유번호는 총 13자리 부호입니다. 확인 후 다시 입력해주시기 바랍니다."
- 입력 안함을 선택하였을 경우 필수 체크 박스는 히든처리.

**Comment by devojy** [comment]
19.01.18 해당 이슈 배포로 close
